Csp 1030 get leaving reasons
SkillsFundingAgency/das-aan-hub-api pull request #166
Opened 2024-01-02 09:18 UTC by MarkFCain

2024-01-03 10:57 UTC, DevenKShah requested changes

2024-01-03 10:57 UTC, DevenKShah commented on src/SFA.DAS.AANHub.Domain/Entities/LeavingReason.cs
> +    public string Description { get; set; } = string.Empty;
This should be initialised with null negation.... `= null!;`

2024-01-03 10:57 UTC, DevenKShah commented on src/SFA.DAS.AANHub.Data/Configuration/LeavingReasonConfiguration.cs
> +        builder.ToTable("LeavingReason");
Could use `nameof (LeavingReason)`

2024-01-03 10:57 UTC, DevenKShah commented on src/SFA.DAS.AANHub.Application/LeavingReasons/Queries/GetLeavingReasons/GetLeavingReasonsQueryResult.cs
> +public record LeavingReasonModel(int Id, string Category, string Description, int Ordering);
What is the point of the model when it is same as Entity?

2024-01-03 10:57 UTC, DevenKShah commented on src/SFA.DAS.AANHub.Application/LeavingReasons/Queries/GetLeavingReasons/GetLeavingReasonsQueryResult.cs
> +            }
This logic should be in the handler

2024-01-03 10:57 UTC, DevenKShah commented on src/SFA.DAS.AANHub.Application/LeavingReasons/Queries/GetLeavingReasons/GetLeavingReasonsQueryResult.cs
> +    public IEnumerable<LeavingReasonModel> LeavingReasons { get; set; } = null!;
Why expose this if it is not being used

2024-01-03 10:57 UTC, DevenKShah commented on src/SFA.DAS.AANHub.Application/LeavingReasons/Queries/GetLeavingReasons/GetLeavingReasonsQueryResult.cs
> +            }
The logic can be simplified, using LINQ
`LeavingReasons.GroupBy(l => l.Category).Select(g => new LeavingCategory { Category = g.Key, LeavingReasons = g.ToList() }).ToList();`

2024-01-03 16:07 UTC, ManishAgarwalDfE submitted a review, later dismissed

2024-01-03 17:19 UTC, ManishAgarwalDfE approved these changes

2024-01-04 14:04 UTC, ManishAgarwalDfE approved these changes

2024-01-04 14:30 UTC, DevenKShah approved these changes

2024-01-04 14:30 UTC, merged